In [1]:
import numpy as np

In [6]:
# Variables
A = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10], 
    [11, 12, 13, 14, 15], 
    [16, 17, 18, 19, 20], 
    [21, 22, 23, 24, 25]
])
B = np.array([100, 101, 102, 103, 104])
print('---- Matriz A ----\n', A)
print('---- Vector B ----\n', B)
print('---- A + B (broadcasting) ----\n', A + B)

---- Matriz A ----
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---- Vector B ----
 [100 101 102 103 104]
---- A + B (broadcasting) ----
 [[101 103 105 107 109]
 [106 108 110 112 114]
 [111 113 115 117 119]
 [116 118 120 122 124]
 [121 123 125 127 129]]
