In [1]:
import numpy as np

In [7]:
A = np.array([[2,3],[5,7],[11,13]])
B = np.array([[1,3],[2,1]])
C = np.array([[3,1],[4,2]])
print('\n--- A ---\n', A)
print('\n--- B ---\n', B)
print('\n--- C ---\n', C)


--- A ---
 [[ 2  3]
 [ 5  7]
 [11 13]]

--- B ---
 [[1 3]
 [2 1]]

--- C ---
 [[3 1]
 [4 2]]


In [8]:
# Product is asociative: A @ (B @ C) = (A @ B) @ C
print(A.dot(B.dot(C)) == A.dot(B).dot(C))

[[ True  True]
 [ True  True]
 [ True  True]]


In [9]:
# Product is distributive: A @ (B + C) = A @ B + A @ C
print(A.dot(B + C) == A.dot(B) + A.dot(C))

[[ True  True]
 [ True  True]
 [ True  True]]


In [11]:
# Product is NOT conmutative: B @ C != C @ B
print(B.dot(C) == C.dot(B))

[[False False]
 [False False]]


In [17]:
# Product of vectors IS conmutative: D @ C = C @ D
C = np.array([1, 2, 3])
D = np.array([4, 5, 6])
print(C.dot(D) == D.dot(C))

True
