In [1]:
import numpy as np

In [11]:
# Variables
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2], [3, 4], [5, 6]])
tensor = np.array([
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])

In [26]:
# A_t = A.T
vector_t = vector.T
matriz_t = matriz.T
tensor_t = tensor.T
print(f'\nVector: \nSize: {vector.size}, Shape: {vector.shape}')
print('Old:\n', vector, '\nNew:\n', vector_t)
print(f'Vector_t: \nSize: {vector_t.size}, Shape: {vector_t.shape}')

print(f'\nMatriz: \nSize: {matriz.size}, Shape: {matriz.shape}')
print('Old:\n', matriz, '\nNew:\n', matriz_t)
print(f'Matriz_t: \nSize: {matriz_t.size}, Shape: {matriz_t.shape}')

print(f'\nTensor: \nSize: {tensor.size}, Shape: {tensor.shape}')
print('Old:\n', tensor, '\nNew:\n', tensor_t)
print(f'Tensor_t: \nSize: {tensor_t.size}, Shape: {tensor_t.shape}')


Vector: 
Size: 3, Shape: (3,)
Old:
 [1 2 3] 
New:
 [1 2 3]
Vector_t: 
Size: 3, Shape: (3,)

Matriz: 
Size: 6, Shape: (3, 2)
Old:
 [[1 2]
 [3 4]
 [5 6]] 
New:
 [[1 3 5]
 [2 4 6]]
Matriz_t: 
Size: 6, Shape: (2, 3)

Tensor: 
Size: 6, Shape: (3, 2, 1)
Old:
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]] 
New:
 [[[1 3 5]
  [2 4 6]]]
Tensor_t: 
Size: 6, Shape: (1, 2, 3)


In [31]:
# C = A + B
A = np.array([
    [1, 2, 3, 4, 5], 
    [6, 7, 8, 9, 10], 
    [11, 12, 13, 14, 15], 
    [16, 17, 18, 19, 20], 
    [21, 22, 23, 24, 25]
])
A_t = A.T
print('---- Matriz A ----\n', A)
print('---- Matriz A transpuesta ----\n', A_t)
print('---- A + A_t ----\n', A + A_t)

---- Matriz A ----
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---- Matriz A transpuesta ----
 [[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]
---- A + A_t ----
 [[ 2  8 14 20 26]
 [ 8 14 20 26 32]
 [14 20 26 32 38]
 [20 26 32 38 44]
 [26 32 38 44 50]]
