In [1]:
import numpy as np

In [35]:
# Matriz identidad: A @ identidad = A
identidad = np.eye(4)
print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
matriz = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
print(identidad.dot(matriz))

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [47]:
# Matriz inversa: A * (A_inversa) = identidad
A = np.array([
    [-1, 0, 1],
    [0, 0, 1],
    [1, -1, 1]
])
A_inversa = np.linalg.inv(A)
print('\n--- A ---\n', A)
print('\n--- A^-1 ---\n', A_inversa)
print('\n--- (A)(A^-1) ---\n', A.dot(A_inversa))


--- A ---
 [[-1  0  1]
 [ 0  0  1]
 [ 1 -1  1]]

--- A^-1 ---
 [[-1.  1. -0.]
 [-1.  2. -1.]
 [ 0.  1.  0.]]

--- (A)(A^-1) ---
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
# Matriz singular: matriz que no tiene una matriz inversa

In [45]:
B = np.array([
    [1, 1],
    [1, 1]
])
B_inversa = np.linalg.inv(B) # Singular Matrix error

LinAlgError: Singular matrix