In [1]:
import numpy as np

In [28]:
# Variables
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])

In [29]:
# [ [A(0, 0)B(0, 0), A(0, 1)B(0, 1), A(0, 2)B(0, 2)], 
# [A(1, 0)B(0, 0), A(1, 1)B(0, 1), A(1, 2)B(0, 2)], 
# [A(2, 0)B(0, 0), A(2, 1)B(0, 1), A(2, 2)B(0, 2)] ]
print(A * B)

[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [30]:
# [ A(0, 0)B(0, 0)+A(0, 1)B(0, 1)+A(0, 2)B(0, 2), 
# A(1, O)B(0, 0)+A(1, 1)B(0, 1)+A(1, 2)B(0, 2), 
# A(2, 0)B(0, 0)+A(2, 1)B(0, 1)+A(2, 2)B(0, 2) ]
print(A.dot(B))
print(np.dot(A, B))

[140 320 500]
[140 320 500]
