In [1]:
import numpy as np

In [2]:
matriz = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])
print(matriz)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
# Matriz ortogonal: Que todos los vectores formados por sus filas son ortonormales y tambien 
# los vectores formados por sus columnas son ortonormales ->
print(matriz[:, 0].dot(matriz[:, 1])) # out: 0 -> columnas ortogonales
print(matriz[:, 0].dot(matriz[:, 2])) # out: 0 -> columnas ortogonales
print(matriz[:, 1].dot(matriz[:, 2])) # out: 0 -> columnas ortogonales

print(np.linalg.norm(matriz[:, 0])) # out: 1 -> columna ortonormal
print(np.linalg.norm(matriz[:, 1])) # out: 1 -> columna ortonormal
print(np.linalg.norm(matriz[:, 2])) # out: 1 -> columna ortonormal

0
0
0
1.0
1.0
1.0


In [4]:
print(matriz[0].dot(matriz[1])) # out: 0 -> filas ortogonales
print(matriz[0].dot(matriz[2])) # out: 0 -> filas ortogonales
print(matriz[1].dot(matriz[2])) # out: 0 -> filas ortogonales

print(np.linalg.norm(matriz[0])) # out: 1 -> fila ortonormal
print(np.linalg.norm(matriz[1])) # out: 1 -> fila ortonormal
print(np.linalg.norm(matriz[2])) # out: 1 -> fila ortonormal

0
0
0
1.0
1.0
1.0


In [5]:
# Propiedades de matrices ortogonales:
# (A)(A.T) = (A.T)(A) = matriz_identidad
# A.T = A^-1

# Warning
La capacidad computacional puede provocar errores al tratar, por ejemplo, números cercanos a cero representando un cero. Ejemplo 1/0 no está definido, pero 1/(1e-18) si lo está (y da algo muy grande, lo que podría aumentar el error)