In [1]:
import numpy as np

In [2]:
# Variables
v1 = np.array([2, 3, 4, 5])

In [3]:
# Matriz diagonal: matriz con los elementos del vector en la diagonal
matriz_diagonal = np.diag(v1)
print(matriz_diagonal)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [4]:
# Inversa de la matriz diagonal es la diagonal de los inversos de los elementos con que se construyo
print(np.linalg.inv(matriz_diagonal))

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [5]:
print(np.diag(1/v1)) # Are equals!!!

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [6]:
# Matriz simetrica => A = A.T
matriz = np.array([
    [1, 2, 3],
    [2, -11, 4],
    [3, 4, 0.5]
])
print(matriz)

[[  1.    2.    3. ]
 [  2.  -11.    4. ]
 [  3.    4.    0.5]]


In [7]:
print(matriz.T) # Are equals!!!

[[  1.    2.    3. ]
 [  2.  -11.    4. ]
 [  3.    4.    0.5]]
